### ISSUE TITLE
transcriptie in volledig scherm werkt niet als je niet ingelogd bent

### ISSUE THREAD

**Issue by samalloing** [libis/Schatkamer#44]
Laat het volledig scherm bij de transcriptie pas zien als de user is ingelogd. Want als je er opklikt en je bent niet ingeschreven krijg je een leeg scherm

**Comment by JorisLambrechts** [comment]
https://github.com/libis/Schatkamer/commit/4e158fbe2716e35460b22501b992cda1f8817250 (en vorige commits)
