### ISSUE TITLE
mediawiki op github

### ISSUE THREAD

**Issue by samalloing** [libis/Schatkamer#71]
waar staat de code van mediawiki op github?

**Comment by JorisLambrechts** [comment]
sinds 5 minuten geleden hier: https://github.com/libis/schatkamer-mediawiki

**Comment by samalloing** [comment]
er is geen capistrano script voor de opzet denk ik

**Comment by JorisLambrechts** [comment]
Heb er dit van gemaakt: https://github.com/libis/heron_configuratie/tree/master/Omeka/capistrano_omeka/mediawiki_schatkamer

Ik deploy voorlopig alles buiten LocalSettings.php dat wordt opgeladen zoals de .htaccess files bij de omeka deployments. Moet nog bekijken wat er nog weggelaten kan/moet worden.

**Comment by samalloing** [comment]
verwijder wel de htaccess file uit de capistrano folder aangezien er geen op de server staat
