### ISSUE TITLE
resetten paswoord mediawiki

### ISSUE THREAD

**Issue by samalloing** [libis/Schatkamer#73]
Kan paswoord gereset worden via mediawiki door de gebruiker?

**Comment by JorisLambrechts** [comment]
via deze link kan het: http://iterdigitalicum.bib.kuleuven.be/schatkamer_mediawiki/index.php/Speciaal:WachtwoordOpnieuwInstellen

via de api lukt dit wel niet

**Comment by samalloing** [comment]
Kan je deze link dan ergens op de schatkamer plaatsen (vb op de login pagina). Zodat mensen hun paswoord kunnen resetten.
