### ISSUE TITLE
mediawiki landingpage aanpassen 

### ISSUE THREAD

**Issue by samalloing** [libis/Schatkamer#76]
Als de gebruiker op de link klikt voor de bevestiging van zijn mail adres, dan komt hij in mediawiki terecht. Deze pagina zou een tekst en link moeten bevatten naar de schatkamer

**Comment by JorisLambrechts** [comment]
https://github.com/libis/schatkamer-mediawiki/commit/302886ebb3005e84043a69e3d6df91d548fcb8b9
