### ISSUE TITLE
badges verdwijnen niet na toevoeging backpack

### ISSUE THREAD

**Issue by samalloing** [libis/Schatkamer#81]
Als een badge wordt toegevoegd aan je backpack en je gaat terug naar scripto. Dan staat er terug dat je een badge verdiend hebt (dezelfde badge), als je dan weer op de link klikt, dan zegt Mozilla dat die badge al toegeveogd is.

**Comment by JorisLambrechts** [comment]
Is dit een testuser? De link met de badge verschijnt alleen als de user + badge nog niet in de databank zit. Maar aangezien hij de badge al heeft volgens mozilla zal het bewijs daarvan (het record in de databank) om de een of andere manier verwijderd zijn.

De user + badge wordt pas in de databank gestoken als mozilla een 'succes' terug geeft wat in dit geval niet meer mogelijk is.
